### ISSUE TITLE
Broken in macOS 12.3 (Apple removed python 2.7)

### ISSUE THREAD

**Issue by elalemanyo** [techouse/alfred-tailwindcss-docs#1]
Hi,
Apple removed python 2.7 from the OS, now the workflow stop working 😞

Thanks for this nice workflow!

**Comment by techouse** [comment]
I'm aware of Apple removing all scripting languages, but there's nothing I can do at this point, because the underlying package (deanishe/alfred-workflow)[https://github.com/deanishe/alfred-workflow] still relies on Python 2. You can check out the issue here https://github.com/deanishe/alfred-workflow/issues/97

Until a Python 3 version pops up that will remain an issue.

**Comment by techouse** [comment]
I'll migrate this over to Dart sometime next week. Already did that for one of my other Python workflows. :)

**Comment by techouse** [comment]
So [v2.0.0](https://github.com/techouse/alfred-tailwindcss-docs/releases/tag/v2.0.0) is now written in Dart and compiled into a standalone exe. This should work without any interruptions. :)

**Comment by elalemanyo** [comment]
> So [v2.0.0](https://github.com/techouse/alfred-tailwindcss-docs/releases/tag/v2.0.0) is now written in Dart and compiled into a standalone exe. This should work without any interruptions. :)

Thanks @techouse! It works perfectly! 👏👏
